title: Blog of Litchi Pi
email: litchi.pi@proton.me
description: >- # this means to ignore newlines until "baseurl:"
    Just writing about Rust stuff, Python automation, random tech subjects,
    and anything related to the world, virtual or not, dreamt or real.
baseurl: "/"
domain: "litchipi.github.io"
url: "https://litchipi.github.io"
author:
    name: "Litchi pi"
    email: "litchi.pi@proton.me"
    github: "https://github.com/litchipi/"
    twitter: "https://twitter.com/LitchiPi"
twitter_username: LitchiPi
github_username:  litchipi

markdown: kramdown
kramdown:
  parse_block_html: true

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-avatar

# Forbidden by Github Pages
# jekyll-archives:
#   enabled:
#     - categories
#   layouts:
#     category: categories
#   permalinks:
#     category: '/category/:name.html'

exclude:
    - _posts/2021-09-13-helloworld*
    - _posts/2021-09-13-test*
    - flake.lock
    - Gemfile*
    - flake*
    - gemset.nix
    - post_ideas
    - serve.sh
    - LICENSE
    - notes
